tasks:
  - init: |
      echo 'TODO: build project'
      python3 -m venv /workspace/enca-cooks/.venv
      source /workspace/enca-cooks/.venv/bin/activate
      python3 -m pip install --upgrade pip
      pip install -r requirements.txt
      deactivate
    command: |
      echo 'TODO: start app'
      source /workspace/enca-cooks/.venv/bin/activate
ports:
  - port: 8080

vscode:
  extensions:
    - ms-python.python