name: enca-cooks
dependencies:
  - numpy
  - pandas
  - flask
  - ipykernel
  - pip
  - pip:
    - todoist-api-python
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib